### ISSUE TITLE
fix the nltk 'punkt' error

### ISSUE THREAD

**Issue by goswamig** [b0noI/dialog_converter#7]
f45c89a20de7:dialog_converter gauta$ python3 converter.py
Traceback (most recent call last):
  File "converter.py", line 10, in <module>
    SENT_DETECTOR = nltk.data.load('tokenizers/punkt/english.pickle')
  File "/usr/local/lib/python3.6/site-packages/nltk/data.py", line 836, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python3.6/site-packages/nltk/data.py", line 954, in _open
    return find(path_, path + ['']).open()
  File "/usr/local/lib/python3.6/site-packages/nltk/data.py", line 675, in find
    raise LookupError(resource_not_found)
import nltk.data
LookupError:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  Searched in:
    - '/Users/gauta/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/nltk_data'
    - '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/share/nltk_data'
    - '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/nltk_data'
    - ''
**********************************************************************

Fix: Just add the below line.

+nltk.download('punkt')
+
 SENT_DETECTOR = nltk.data.load('tokenizers/punkt/english.pickle')

**Comment by contefranz** [comment]
This indeed solved my problem. Not sure why though it worked

**Comment by codebrain001** [comment]
Thanks...helped me too

**Comment by ghost** [comment]
it worked ....

**Comment by Chaampz** [comment]
This worked. Thanks

**Comment by sscswapnil** [comment]
Thanks for the Help

**Comment by MengshiGeMoncy** [comment]
It works. thanks for the help.

**Comment by abhi7585** [comment]
Where to add those lines?

**Comment by SaloniGandhi** [comment]
!pip install nltk
nltk.download('punkt')

**Comment by paul2048** [comment]
If you have your VPN on, make sure you turn it off.
I turned it off, ran `nltk.download('punkt')` and then it finally worked.

**Comment by kubasiak** [comment]
I downloaded 'punkt' and still have got the same problem

[nltk_data] Downloading package punkt to
[nltk_data]   Package punkt is already up-to-date!

LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')

**Comment by gentlee66** [comment]
I wasn't able to download punkt via nltk, so I found this thread on Stack which helped me.
https://stackoverflow.com/questions/38916452/nltk-download-ssl-certificate-verify-failed
